version: '3'
services:
  aspnetcore-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=gateway01.ap-southeast-1.prod.aws.tidbcloud.com;Port=4000;Database=EMPLOYEES;Uid=2VnVXK5gW49FXpR.root;Pwd=ng5t4JNP7v51MAjK;
